### ISSUE TITLE
springboot上使用connectWithSpringSupport测试报错

### ISSUE THREAD

**Issue by xxxlihui** [vincentlauvlwj/Ktorm#111]

**Comment by xxxlihui** [comment]
`java.lang.UnsupportedOperationException: Transaction is managed by Spring, please use Spring's @Transactional annotation instead.

	at me.liuwj.ktorm.database.SpringManagedTransactionManager.newTransaction(SpringManagedTransactionManager.kt:44)
	at me.liuwj.ktorm.database.SpringManagedTransactionManager.newTransaction(SpringManagedTransactionManager.kt:34)
	at me.liuwj.ktorm.database.SqlDialect$DefaultImpls.executeUpdateAndRetrieveKeys(SqlDialect.kt:115)
	at me.liuwj.ktorm.database.SqlDialectKt$detectDialectImplementation$1.executeUpdateAndRetrieveKeys(SqlDialect.kt:103)
	at me.liuwj.ktorm.database.Database.executeUpdateAndRetrieveKeys(Database.kt:363)
	at me.liuwj.ktorm.entity.EntityDmlKt.add(EntityDml.kt:84)`
`@SpringBootTest
class LogisticApplicationTests {

    @Autowired
    lateinit var database: Database

    @Test
    fun contextLoads() {

        database.sequenceOf(PurchaseHeadTable).add(PurchaseHead{
            this.billCode="12121212"
        })
        for (i in database.sequenceOf(PurchaseHeadTable).toList()) {
            println(i)
        }

    }


}`

**Comment by vincentlauvlwj** [comment]
请升级到 [2.7.2](https://github.com/vincentlauvlwj/Ktorm/releases/tag/v2.7.2) 版本
