### ISSUE TITLE
Support for mocking/unit tests

### ISSUE THREAD

**Issue by JoonasC** [vincentlauvlwj/Ktorm#121]
When testing application logic it would be useful to have a certain query always return a certain result without needing to be connected to a database.
For example Ktor offers `withTestApplication`, which enables easily making calls to routes without needing to actually run the server: [https://ktor.io/servers/testing.html](https://ktor.io/servers/testing.html), and it would be nice if Ktorm supported a similar mode, which would let you specify query results in advance without needing a connection to a database.

Currently I have tried to achieve this with mocking using MockK [https://github.com/mockk/mockk](https://github.com/mockk/mockk), but it hasn't really been working:
```
val database: Database = mockk()

every { database.sequenceOf(Users).find { it.username eq "testuser" } } returns User {
  username = "testuser"
  fullName = "Test Tester"
  email = "test@test.com"
  passwordHash = "\$2a\$14\$UDvhFC/ILlphkTFt9ZYu0uEGXESWcL.SDDro/qZ4DD9/UfWP7AT6S"
 }

val user = database.sequenceOf(Users).find { it.username eq "testuser" }
```
```
java.lang.NullPointerException
	at me.liuwj.ktorm.database.CachedRowSet.next(CachedRowSet.kt:208)
	at me.liuwj.ktorm.database.JdbcExtensionsKt$iterator$1.hasNext(JdbcExtensions.kt:112)
	at me.liuwj.ktorm.entity.EntitySequence$iterator$1.hasNext(EntitySequence.kt:136)
	at kotlin.sequences.SequencesKt___SequencesKt.firstOrNull(_Sequences.kt:129)
	at me.liuwj.ktorm.entity.EntitySequenceKt.elementAtOrNull(EntitySequence.kt:859)
	at tests.apiTests.UserApiTests$1$1.invoke(UserApiTests.kt:93)
	at tests.apiTests.UserApiTests$1$1.invoke(UserApiTests.kt:29)
	at io.mockk.impl.eval.RecordedBlockEvaluator$record$block$1.invoke(RecordedBlockEvaluator.kt:24)
	at io.mockk.impl.eval.RecordedBlockEvaluator$enhanceWithNPERethrow$1.invoke(RecordedBlockEvaluator.kt:74)
	at io.mockk.impl.recording.JvmAutoHinter.autoHint(JvmAutoHinter.kt:23)
	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:36)
	at io.mockk.impl.eval.EveryBlockEvaluator.every(EveryBlockEvaluator.kt:30)
	at io.mockk.MockKDsl.internalEvery(API.kt:92)
	at io.mockk.MockKKt.every(MockK.kt:104)
	at tests.apiTests.UserApiTests$1.invoke(UserApiTests.kt:38)
	at tests.apiTests.UserApiTests$1.invoke(UserApiTests.kt:29)
	at io.kotest.core.spec.TestConfiguration$beforeSpec$1.beforeSpec(configuration.kt:112)
	at io.kotest.core.runtime.CallbacksKt.invokeBeforeSpec(callbacks.kt:75)
	at io.kotest.core.engine.SingleInstanceSpecRunner$execute$3.invokeSuspend(SingleInstanceSpecRunner.kt:78)
	at io.kotest.core.engine.SingleInstanceSpecRunner$execute$3.invoke(SingleInstanceSpecRunner.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:177)
	at io.kotest.core.engine.SingleInstanceSpecRunner.execute(SingleInstanceSpecRunner.kt:77)
	at io.kotest.core.engine.SpecExecutor$runTests$run$1.invokeSuspend(SpecExecutor.kt:105)
	at io.kotest.core.engine.SpecExecutor$runTests$run$1.invoke(SpecExecutor.kt)
	at io.kotest.core.engine.SpecExecutor.interceptSpec(SpecExecutor.kt:117)
	at io.kotest.core.engine.SpecExecutor.runTests(SpecExecutor.kt:108)
	at io.kotest.core.engine.SpecExecutor.execute(SpecExecutor.kt:36)
	at io.kotest.core.engine.KotestEngine$submitBatch$$inlined$forEach$lambda$1$1.invokeSuspend(KotestEngine.kt:71)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:272)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:79)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:54)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:36)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at io.kotest.core.engine.KotestEngine$submitBatch$$inlined$forEach$lambda$1.run(KotestEngine.kt:70)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

While I could get this working through mocking with MockK it would require me to familiarize myself with Ktorm's codebase in order to mock it properly, which would be time consuming.

So could this feature be added, or does it exist already? (Haven't seen any mention of unit testing in the documentation)
Thanks.

**Comment by vincentlauvlwj** [comment]
To mock and test database layers, you can use an in-memory database (eg. [H2](http://www.h2database.com/html/main.html)), or [Testcontainsers](https://www.testcontainers.org/).

Ktorm uses Testcontainers, you can find an example of how we use it in [MySqlTest.kt](https://github.com/vincentlauvlwj/Ktorm/blob/master/ktorm-support-mysql/src/test/kotlin/me/liuwj/ktorm/support/mysql/MySqlTest.kt) and [BaseTest.kt](https://github.com/vincentlauvlwj/Ktorm/blob/master/ktorm-core/src/test/kotlin/me/liuwj/ktorm/BaseTest.kt).

**Comment by JoonasC** [comment]
Ok, thanks
