### ISSUE TITLE
Invalid error with PostgreSQL : Pagination is not supported in Standard SQL

### ISSUE THREAD

**Issue by thibaultmeyer** [vincentlauvlwj/Ktorm#68]
It is impossible to do a search with a limit. I get an error :

```
me.liuwj.ktorm.database.DialectFeatureNotSupportedException: Pagination is not supported in Standard SQL.
	at me.liuwj.ktorm.expression.SqlFormatter.writePagination(SqlFormatter.kt:348)
	at me.liuwj.ktorm.expression.SqlFormatter.visitSelect(SqlFormatter.kt:289)
	at me.liuwj.ktorm.expression.SqlExpressionVisitor.visitQuery(SqlExpressionVisitor.kt:89)
	at me.liuwj.ktorm.expression.SqlExpressionVisitor.visit(SqlExpressionVisitor.kt:46)
	at me.liuwj.ktorm.expression.SqlFormatter.visit(SqlFormatter.kt:117)
	at me.liuwj.ktorm.database.Database.formatExpression(Database.kt:239)
	at me.liuwj.ktorm.database.Database.formatExpression$default(Database.kt:232)
```

This is a false positive, because PostgreSQL knows very well how to make a select with a result limitation.

**Comment by vincentlauvlwj** [comment]
Please add this dependency to your project: 

```xml
<dependency>
    <groupId>me.liuwj.ktorm</groupId>
    <artifactId>ktorm-support-postgresql</artifactId>
    <version>${ktorm.version}</version>
</dependency>
```

Or Gradle: 

```groovy
compile "me.liuwj.ktorm:ktorm-support-postgresql:${ktorm.version}"
```

**Comment by thibaultmeyer** [comment]
yes it working.

Thank you !!
